@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":BizBookParser" as BizBookParser LOGIC_COLOR
participant ":EditCommandParser" as EditCommandParser LOGIC_COLOR
participant "e:EditCommand" as EditCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("edit 1 s/Interviewing")
activate LogicManager

LogicManager -> BizBookParser : parseCommand("edit 1 s/Interviewing")
activate BizBookParser

create EditCommandParser
BizBookParser -> EditCommandParser
activate EditCommandParser

EditCommandParser --> BizBookParser
deactivate EditCommandParser

BizBookParser -> EditCommandParser : parse("1 s/Interviewing")
activate EditCommandParser

create EditCommand
EditCommandParser -> EditCommand
activate EditCommand

EditCommand --> EditCommandParser : returns EditCommand
deactivate EditCommand

EditCommandParser --> BizBookParser : e
deactivate EditCommandParser
EditCommandParser -[hidden]-> BizBookParser
destroy EditCommandParser

BizBookParser --> LogicManager : e
deactivate BizBookParser

LogicManager -> EditCommand : execute(m)
activate EditCommand

EditCommand -> Model : getFilteredInternshipApplicationList()
activate Model

Model --> EditCommand : filteredList
deactivate Model

EditCommand -> Model : setInternshipApplication(applicationToEdit, editedApplication)
activate Model

Model --> EditCommand
deactivate Model

EditCommand -> Model : updateFilteredInternshipApplicationList(PREDICATE_SHOW_ALL_APPLICATIONS)
activate Model

Model --> EditCommand
deactivate Model

create CommandResult
EditCommand -> CommandResult
activate CommandResult

CommandResult --> EditCommand
deactivate CommandResult

EditCommand --> LogicManager : r
deactivate EditCommand

[<--LogicManager
deactivate LogicManager
@enduml

